# Generated by Django 2.0.3 on 2018-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='19700101', max_length=10, verbose_name='code')),
                ('unique_id', models.CharField(max_length=15, verbose_name='unique_id')),
                ('subject', models.CharField(default='-', max_length=10, verbose_name='subject')),
                ('bloodpressure', models.CharField(default='-', max_length=10, verbose_name='bloodpressure')),
                ('bloodsugar', models.CharField(default='-', max_length=10, verbose_name='bloodsugar')),
                ('height', models.CharField(default='-', max_length=10, verbose_name='height')),
                ('weight', models.CharField(default='-', max_length=10, verbose_name='weight')),
                ('remark', models.CharField(default='-', max_length=3000, verbose_name='remark')),
                ('log_id', models.CharField(default='-', max_length=30, verbose_name='log_id')),
                ('is_done', models.IntegerField(default=0, verbose_name='is_done')),
                ('timeDate', models.CharField(default='19700101', max_length=8, verbose_name='timeDate')),
                ('timeTime', models.CharField(default='000000', max_length=6, verbose_name='timeTime')),
            ],
        ),
        migrations.CreateModel(
            name='contactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_id', models.CharField(max_length=15, unique=True, verbose_name='home_id')),
                ('address', models.CharField(default='-', max_length=100, verbose_name='address')),
                ('telephone', models.CharField(default='-', max_length=14, verbose_name='telephone')),
                ('host', models.CharField(default='-', max_length=100, verbose_name='host')),
                ('family_stats', models.CharField(default='-', max_length=500, verbose_name='family_stats')),
                ('description', models.CharField(default='-', max_length=3000, verbose_name='description')),
                ('remark', models.CharField(default='-', max_length=3000, verbose_name='remark')),
            ],
        ),
        migrations.CreateModel(
            name='cureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(default='-', max_length=30, verbose_name='log_id')),
                ('unique_id', models.CharField(default='DEFAULT', max_length=15, verbose_name='unique_id')),
                ('timeDate', models.CharField(default='19700101', max_length=8, verbose_name='timeDate')),
                ('timeTime', models.CharField(default='000000', max_length=6, verbose_name='timeTime')),
                ('problem_tmp', models.CharField(default='-', max_length=3000, verbose_name='problem_tmp')),
                ('solution_tmp', models.CharField(default='-', max_length=3000, verbose_name='solution_tmp')),
                ('medicine_tmp', models.CharField(default='-', max_length=3000, verbose_name='medicine_tmp')),
                ('medicine_tmp_appendix', models.CharField(default='無', max_length=3000, verbose_name='medicine_tmp_appendix')),
                ('remark', models.CharField(default='-', max_length=3000, verbose_name='remark')),
                ('subject', models.CharField(default='-', max_length=10, verbose_name='subject')),
                ('is_taken', models.IntegerField(default=0, verbose_name='is_taken')),
            ],
        ),
        migrations.CreateModel(
            name='medicineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(default='-', max_length=50, verbose_name='medicine_name')),
                ('medicine_expiry', models.CharField(default='1970-01-01', max_length=10, verbose_name='medicine_expiry')),
                ('medicine_unit', models.CharField(default='-', max_length=10, verbose_name='medicine_unit')),
                ('medicine_count', models.IntegerField(default=0, verbose_name='medicine_count')),
            ],
        ),
        migrations.CreateModel(
            name='nicknameTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=15, verbose_name='unique_id')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('is_new', models.IntegerField(default=1, verbose_name='is_new')),
            ],
        ),
        migrations.CreateModel(
            name='patientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=15, unique=True, verbose_name='unique_id')),
                ('location', models.CharField(default='-', max_length=5, verbose_name='location')),
                ('gender', models.CharField(default='-', max_length=10, verbose_name='gender')),
                ('id_card_number', models.CharField(default='-', max_length=15, verbose_name='id_card_number')),
                ('birthday', models.CharField(default='-', max_length=15, verbose_name='birthday')),
                ('bloodtype', models.CharField(default='-', max_length=10, verbose_name='bloodtype')),
                ('mobile1', models.CharField(default='-', max_length=14, verbose_name='mobile1')),
                ('mobile2', models.CharField(default='-', max_length=14, verbose_name='mobile2')),
                ('telephone1', models.CharField(default='-', max_length=14, verbose_name='telephone1')),
                ('telephone2', models.CharField(default='-', max_length=14, verbose_name='telephone2')),
                ('is_alive', models.CharField(default=True, max_length=10, verbose_name='is_alive')),
            ],
        ),
    ]
